version: '2.1'

services:
  auth:
    build: auth/
    volumes:
      - ./auth/ :/auth/
    expose:
      - "13451"
  chat:
    build: chat/
    volumes:
      - ./chat/ :/chat/
    expose:
      - "13452"
  classification:
    build: classification/
    volumes:
      - ./classification/ :/classification/
    expose:
      - "13453"
  proxy:
    restart: always
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "192.168.1.3:80:80"
    links:
      - auth
      - chat
      - classification
